"install thogen#infect()

let $VIRTUAL_ENV = $VIRTUAL_ENV

call plug#begin('~/.vim/plugged')

Plug 'scrooloose/nerdtree'
Plug 'davidhalter/jedi-vim'
Plug 'nanotech/jellybeans.vim'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-git'
Plug 'tpope/vim-fugitive'
Plug 'vim-airline/vim-airline'
Plug 'jmcantrell/vim-virtualenv'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'jlanzarotta/bufexplorer'
Plug 'scrooloose/syntastic'
Plug 'majutsushi/tagbar'
Plug 'mattn/emmet-vim'

call plug#end()

syntax on
filetype plugin indent on

set keymap=russian-jcukenwin
set iminsert=0
set imsearch=0
set number
highlight lCursor guifg=NONE guibg=Cyan
" set background=dark
set t_Co=256
colorscheme jellybeans

" ================ Persistent Undo ==================
" Keep undo history across sessions, by storing in file.
" Only works all the time.
if has('persistent_undo')
  silent !mkdir ~/.vim/backups > /dev/null 2>&1
  set undodir=~/.vim/backups
  set undofile
endif

filetype plugin indent on
" show existing tab with 4 spaces width
set tabstop=4
" when indenting with '>', use 4 spaces width
set shiftwidth=4
" On pressing tab, insert 4 spaces
set expandtab


set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_python_checkers=['flake8']
let g:syntastic_python_flake8_args='--ignore=E501,E225'


" Keys "
let mapleader=","


" Allow to copy/paste between VIM instances
" "copy the current visual selection to ~/.vbuf
vmap <Leader>y :w! ~/.vbuf<CR>
" "copy the current line to the buffer file if no visual selection
nmap <Leader>y :.w! ~/.vbuf<CR>
" "paste the contents of the buffer file
nmap <Leader>p :r ~/.vbuf<CR>

" "paste foreign data
set pastetoggle=<F2>

" Work with buffers
nnoremap <leader>b :BufExplorer<CR>
" " Next buffer
map <Leader>a :bnext<Return>
" " Prev buffer
map <Leader>s :bprev<Return>
" " Close buffer
map <Leader>x :bd<Return>


nmap <C-\> :NERDTreeFind<CR>
nmap <silent> <leader><leader> :NERDTreeToggle<CR>
let NERDTreeIgnore = ['\.pyc$']
let NERDTreeQuitOnOpen=1

let g:airline#extensions#tabline#enabled = 1

let g:virtualenv_directory = $VIRTUAL_ENV
let g:virtualenv_auto_activate = 1

nnoremap <silent> <F9> :TagbarToggle<CR>
